//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Ticket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hall1
    {
        public int id { get; set; }
        public string Hall { get; set; }
    
        public virtual Film Film { get; set; }
    }
}
