//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema_Ticket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CinEntities1 : DbContext
    {
        public CinEntities1()
            : base("name=CinEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authorisation> authorisation { get; set; }
        public virtual DbSet<Film> Film { get; set; }
        public virtual DbSet<Hall1> Hall1 { get; set; }
        public virtual DbSet<Place1> Place1 { get; set; }
        public virtual DbSet<PlaceRow1> PlaceRow1 { get; set; }
        public virtual DbSet<Row1> Row1 { get; set; }
        public virtual DbSet<Sess> Sess { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Activity> Activity { get; set; }
    }
}
